### ISSUE TITLE
Main Task List

### ISSUE THREAD

**Issue by TheMechanist1** [TheMechanist1/Spod-Proc#1]
## Purpose
This will serve as the central task list for my project. Hopefully, this will help with organization and keep me from getting too distracted by something random. This issue will be updated in the future to add more ideas and whatnot.

### The Plan
- [x] Convert Json file to object
- [x] Make a sortable list of said objects
- [x] Sort by TS
- [ ] Sort by times listened
- [ ] Get all the different reason start and reason end values and make an enum with them
- [ ] Sort by the device used
